# Generated by Django 4.1.4 on 2024-05-12 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_follow_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписку', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelTable(
            name='follow',
            table='подписка',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='профиль',
        ),
        migrations.AlterModelTable(
            name='user',
            table='аккаунт',
        ),
    ]
